/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_MysqlConn;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.*;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;     

/**
 *
 * @author Theo
 */
public class applies_frame extends javax.swing.JFrame {

    
    private static final String username = "root";
    private static final String password = "12345theo";
    private static final String DB_URL = "jdbc:mysql://localhost:3306/project2";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int q, i, id, deleteItem;
    
    public applies_frame() {
        initComponents();
        upDateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    //=============================FUNCTION==========================//
    
    public void upDateDB()
    {
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("Select * FROM applies");
            
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next())
            {
                Vector columnData = new Vector();
                
                for (i = 1; i<= q; i++)
                {
                    columnData.add(rs.getString("em_username"));
                    columnData.add(rs.getInt("job_id"));
                    columnData.add(rs.getDate("date_of_submission"));
                    columnData.add(rs.getString("status"));
                    columnData.add(rs.getString("evaluator1"));
                    columnData.add(rs.getInt("score1"));
                    columnData.add(rs.getString("evaluator2"));
                    columnData.add(rs.getInt("score2"));
                    
                }
                
                RecordTable.addRow(columnData);
            }                
        }
        catch(Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username_label = new javax.swing.JLabel();
        Password_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        lastname_label = new javax.swing.JLabel();
        reg_date_label = new javax.swing.JLabel();
        email_label = new javax.swing.JLabel();
        em_username_text = new javax.swing.JTextField();
        job_id_text = new javax.swing.JTextField();
        date_of_submission_text = new javax.swing.JTextField();
        status_text = new javax.swing.JTextField();
        evaluator1_text = new javax.swing.JTextField();
        score1_text = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        insert_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        email_label1 = new javax.swing.JLabel();
        email_label2 = new javax.swing.JLabel();
        evaluator2_text = new javax.swing.JTextField();
        score2_text = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        em_username_table = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        job_id_table = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        evaluator1_table = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        evaluator2_table = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        score1_table = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        score2_table = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        status_table = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        date_of_submission_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Applies");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Username_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Username_label.setText("Em_username");

        Password_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Password_label.setText("job_id");

        name_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_label.setText("date_of_submission");

        lastname_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lastname_label.setText("status");

        reg_date_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reg_date_label.setText("evaluator1");

        email_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_label.setText("score1");

        em_username_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                em_username_textMouseClicked(evt);
            }
        });
        em_username_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em_username_textActionPerformed(evt);
            }
        });

        job_id_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                job_id_textMouseClicked(evt);
            }
        });
        job_id_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                job_id_textActionPerformed(evt);
            }
        });

        date_of_submission_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_of_submission_textMouseClicked(evt);
            }
        });
        date_of_submission_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_of_submission_textActionPerformed(evt);
            }
        });

        status_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                status_textMouseClicked(evt);
            }
        });

        evaluator1_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluator1_textMouseClicked(evt);
            }
        });

        score1_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                score1_textMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "em_username", "job_id", "date_of_submission", "status", "evaluator1", "score1", "evaluator2", "score2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        insert_button.setText("Insert");
        insert_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_buttonActionPerformed(evt);
            }
        });

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        delete_button.setText("Delete");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        exit_button.setText("Exit");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        email_label1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_label1.setText("evaluator2");

        email_label2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_label2.setText("score2");

        evaluator2_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluator2_textMouseClicked(evt);
            }
        });
        evaluator2_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluator2_textActionPerformed(evt);
            }
        });

        score2_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                score2_textMouseClicked(evt);
            }
        });

        em_username_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        em_username_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                em_username_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(em_username_table);

        job_id_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        job_id_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                job_id_tableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(job_id_table);

        evaluator1_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        evaluator1_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluator1_tableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(evaluator1_table);

        evaluator2_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        evaluator2_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluator2_tableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(evaluator2_table);

        score1_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        score1_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                score1_tableMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(score1_table);

        score2_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        score2_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                score2_tableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(score2_table);

        status_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        status_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                status_tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(status_table);

        date_of_submission_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ));
        date_of_submission_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                date_of_submission_tableMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(date_of_submission_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(insert_button)
                            .addComponent(update_button)
                            .addComponent(delete_button)
                            .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Username_label)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reg_date_label)
                                    .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(score1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(evaluator1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(em_username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(job_id_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(email_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(email_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(score2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(evaluator2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(date_of_submission_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(status_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(job_id_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(em_username_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(date_of_submission_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reg_date_label, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evaluator1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(evaluator2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(status_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(score2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(score1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email_label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(insert_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(update_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delete_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reset_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exit_button))))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insert_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_buttonActionPerformed
        
       try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("INSERT INTO applies(em_username, job_id, date_of_submission, "
                    + "status, evaluator1, score1, evaluator2, score2) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
            
            pst.setString(1, em_username_text.getText());
            pst.setString(2, job_id_text.getText());
            pst.setString(3, date_of_submission_text.getText());
            pst.setString(4, status_text.getText());
            pst.setString(5, evaluator1_text.getText());
            pst.setString(6, score1_text.getText());
            pst.setString(7, evaluator2_text.getText());
            pst.setString(8, score2_text.getText());
            
            int rowsUpdates = pst.executeUpdate();
            
            if (rowsUpdates > 0) {
                JOptionPane.showMessageDialog(this, "Record Added.");
            upDateDB();
            } else {
                JOptionPane.showMessageDialog(this, "No changes made. Record not added.");
            }
       }
       
       catch(ClassNotFoundException ex)
       {
           java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE,
                   null, ex);  
       }
       catch(SQLException ex)
       {
           java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE,
                   null, ex);  
       }        
    }//GEN-LAST:event_insert_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
     try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("DELETE FROM applies WHERE em_username = ? AND job_id = ?");
            
            pst.setString(1, em_username_text.getText());
            pst.setString(2, job_id_text.getText());
                        
            int rowsUpdates = pst.executeUpdate();
            
            if (rowsUpdates > 0) {
                JOptionPane.showMessageDialog(this, "Record Deleted.");
            upDateDB();
            } else {
                JOptionPane.showMessageDialog(this, "No changes made. Record not deleted.");
            }
        }
       
       catch(ClassNotFoundException ex)
       {
           java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE,
                   null, ex);  
       }
       catch(SQLException ex)
       {
           java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE,
                   null, ex);  
           
       }   
              
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void date_of_submission_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_of_submission_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_of_submission_textActionPerformed

    private JFrame frame;
    
    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit.", "MySQL User",
               JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
       em_username_text.setText("");
       date_of_submission_text.setText("");
       status_text.setText("");
       evaluator1_text.setText("");
       score1_text.setText("");
       job_id_text.setText("");
       evaluator2_text.setText("");
       score2_text.setText("");
    }//GEN-LAST:event_reset_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("UPDATE applies SET em_username = ?, job_id = ?, date_of_submission = ?, "
                    + "status = ?, evaluator1 = ?, score1 = ?, evaluator2 = ?, score2 = ? "
                    + "WHERE em_username = ? AND job_id = ?");
            
            pst.setString(1, em_username_text.getText());
            pst.setString(2, job_id_text.getText());
            pst.setString(3, date_of_submission_text.getText());
            pst.setString(4, status_text.getText());
            pst.setString(5, evaluator1_text.getText());
            pst.setString(6, score1_text.getText());
            pst.setString(7, evaluator2_text.getText());
            pst.setString(8, score2_text.getText());
            
            pst.setString(9, em_username_text.getText()); // Use the username entered by the user
            pst.setString(10, job_id_text.getText());
            
            int rowsUpdates = pst.executeUpdate();
            
            if (rowsUpdates > 0) {
                JOptionPane.showMessageDialog(this, "Record Updated.");
            upDateDB();
            } else {
                JOptionPane.showMessageDialog(this, "No changes made. Record not updated.");
            }
        }
       
       catch(ClassNotFoundException ex)
       {
           java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE,
                   null, ex);  
       }
       catch(SQLException ex)
       {
           java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE,
                   null, ex);  
           
       }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        em_username_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString()); 
        job_id_text.setText(RecordTable.getValueAt(SelectedRows, 1).toString());   
        date_of_submission_text.setText(RecordTable.getValueAt(SelectedRows, 2).toString());   
        status_text.setText(RecordTable.getValueAt(SelectedRows, 3).toString());   
        evaluator1_text.setText(RecordTable.getValueAt(SelectedRows, 4).toString());   
        score1_text.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        evaluator2_text.setText(RecordTable.getValueAt(SelectedRows, 6).toString());   
        score2_text.setText(RecordTable.getValueAt(SelectedRows, 7).toString());  
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void job_id_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_job_id_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_job_id_textActionPerformed

    private void em_username_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em_username_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em_username_textActionPerformed

    private void evaluator2_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluator2_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evaluator2_textActionPerformed

    private void em_username_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_em_username_tableMouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel)em_username_table.getModel();
        int SelectedRows = em_username_table.getSelectedRow();

        em_username_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString());

        em_username_table.setVisible(false);
    }//GEN-LAST:event_em_username_tableMouseClicked

    private void em_username_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_em_username_textMouseClicked
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("Select username FROM employee");
            
            em_username_table.setVisible(true);
                        
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)em_username_table.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next())
            {
                Vector columnData = new Vector();
                
                for (i = 1; i<= q; i++)
                {
                    columnData.add(rs.getString("username"));
                    
                }
                
                RecordTable.addRow(columnData);
            }                
        }
        catch(Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_em_username_textMouseClicked

    private void job_id_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_job_id_tableMouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel)job_id_table.getModel();
        int SelectedRows = job_id_table.getSelectedRow();

        job_id_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString());

        job_id_table.setVisible(false);

    }//GEN-LAST:event_job_id_tableMouseClicked

    private void job_id_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_job_id_textMouseClicked
            try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("Select id FROM job ORDER BY id ASC");
            
            job_id_table.setVisible(true);
                        
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)job_id_table.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next())
            {
                Vector columnData = new Vector();
                
                for (i = 1; i<= q; i++)
                {
                    columnData.add(rs.getString("id"));
                    
                }
                
                RecordTable.addRow(columnData);
            }                
        }
        catch(Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_job_id_textMouseClicked

    private void evaluator1_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluator1_tableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)evaluator1_table.getModel();
        int SelectedRows = evaluator1_table.getSelectedRow();

        evaluator1_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString());

        evaluator1_table.setVisible(false);
    }//GEN-LAST:event_evaluator1_tableMouseClicked

    private void evaluator1_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluator1_textMouseClicked
           try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("Select username FROM evaluator");
            
            evaluator1_table.setVisible(true);
                        
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)evaluator1_table.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next())
            {
                Vector columnData = new Vector();
                
                for (i = 1; i<= q; i++)
                {
                    columnData.add(rs.getString("username"));
                    
                }
                
                RecordTable.addRow(columnData);
            }                
        }
        catch(Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_evaluator1_textMouseClicked

    private void evaluator2_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluator2_tableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)evaluator2_table.getModel();
        int SelectedRows = evaluator2_table.getSelectedRow();

        evaluator2_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString());

        evaluator2_table.setVisible(false);
    }//GEN-LAST:event_evaluator2_tableMouseClicked

    private void evaluator2_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluator2_textMouseClicked
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("Select username FROM evaluator");
            
            evaluator2_table.setVisible(true);
                        
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)evaluator2_table.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next())
            {
                Vector columnData = new Vector();
                
                for (i = 1; i<= q; i++)
                {
                    columnData.add(rs.getString("username"));
                    
                }
                
                RecordTable.addRow(columnData);
            }                
        }
        catch(Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_evaluator2_textMouseClicked

    private void score1_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_score1_tableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)score1_table.getModel();
        int SelectedRows = score1_table.getSelectedRow();

        score1_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString());

        score1_table.setVisible(false);
    }//GEN-LAST:event_score1_tableMouseClicked

    private void score1_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_score1_textMouseClicked
        try {
        // Assuming average_score_table is your JTable instance

        // Create a DefaultTableModel
        DefaultTableModel model = new DefaultTableModel();
        score1_table.setModel(model);

        // Add a column to the model
        model.addColumn("");

        // Add numbers from 0 to 20 to the table
        for (int i = 0; i <= 20; i++) {
            model.addRow(new Object[]{i});
        }

        // Make the table visible
        score1_table.setVisible(true);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_score1_textMouseClicked

    private void score2_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_score2_tableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)score2_table.getModel();
        int SelectedRows = score2_table.getSelectedRow();

        score2_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString());

        score2_table.setVisible(false);
    }//GEN-LAST:event_score2_tableMouseClicked

    private void score2_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_score2_textMouseClicked
         try {
        // Assuming average_score_table is your JTable instance

        // Create a DefaultTableModel
        DefaultTableModel model = new DefaultTableModel();
        score2_table.setModel(model);

        // Add a column to the model
        model.addColumn("");

        // Add numbers from 0 to 20 to the table
        for (int i = 0; i <= 20; i++) {
            model.addRow(new Object[]{i});
        }

        // Make the table visible
        score2_table.setVisible(true);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
    }//GEN-LAST:event_score2_textMouseClicked

    private void status_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_status_tableMouseClicked

        DefaultTableModel RecordTable = (DefaultTableModel)status_table.getModel();
        int SelectedRows = status_table.getSelectedRow();

        status_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString());

        status_table.setVisible(false);
    }//GEN-LAST:event_status_tableMouseClicked

    private void status_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_status_textMouseClicked
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("Select DISTINCT status FROM applies");
            
            status_table.setVisible(true);
                        
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)status_table.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next())
            {
                Vector columnData = new Vector();
                
                for (i = 1; i<= q; i++)
                {
                    columnData.add(rs.getString("status"));
                    
                }
                
                RecordTable.addRow(columnData);
            }                
        }
        catch(Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_status_textMouseClicked

    private void date_of_submission_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_of_submission_tableMouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel)date_of_submission_table.getModel();
        int SelectedRows = date_of_submission_table.getSelectedRow();

        date_of_submission_text.setText(RecordTable.getValueAt(SelectedRows, 0).toString());

        date_of_submission_table.setVisible(false);
    }//GEN-LAST:event_date_of_submission_tableMouseClicked

    private void date_of_submission_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date_of_submission_textMouseClicked
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(DB_URL,username,password);
            pst = sqlConn.prepareStatement("Select DISTINCT date_of_submission FROM applies");
            
            date_of_submission_table.setVisible(true);
                        
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            
            q = stData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)date_of_submission_table.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next())
            {
                Vector columnData = new Vector();
                
                for (i = 1; i<= q; i++)
                {
                    columnData.add(rs.getString("date_of_submission"));
                    
                }
                
                RecordTable.addRow(columnData);
            }                
        }
        catch(Exception ex) 
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_date_of_submission_textMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applies_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applies_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Password_label;
    private javax.swing.JLabel Username_label;
    private javax.swing.JTable date_of_submission_table;
    private javax.swing.JTextField date_of_submission_text;
    private javax.swing.JButton delete_button;
    private javax.swing.JTable em_username_table;
    private javax.swing.JTextField em_username_text;
    private javax.swing.JLabel email_label;
    private javax.swing.JLabel email_label1;
    private javax.swing.JLabel email_label2;
    private javax.swing.JTable evaluator1_table;
    private javax.swing.JTextField evaluator1_text;
    private javax.swing.JTable evaluator2_table;
    private javax.swing.JTextField evaluator2_text;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton insert_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable job_id_table;
    private javax.swing.JTextField job_id_text;
    private javax.swing.JLabel lastname_label;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel reg_date_label;
    private javax.swing.JButton reset_button;
    private javax.swing.JTable score1_table;
    private javax.swing.JTextField score1_text;
    private javax.swing.JTable score2_table;
    private javax.swing.JTextField score2_text;
    private javax.swing.JTable status_table;
    private javax.swing.JTextField status_text;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
