/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_MysqlConn;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.*;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;     

/**
 *
 * @author Theo
 */
public class main_frame extends javax.swing.JFrame {

    
    private static final String username = "root";
    private static final String password = "12345theo";
    private static final String DB_URL = "jdbc:mysql://localhost:3306/project2";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int q, i, id, deleteItem;
    
    public main_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    

    
      
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etaireia_table = new javax.swing.JButton();
        applies_button = new javax.swing.JButton();
        promotion_log = new javax.swing.JButton();
        languages_button = new javax.swing.JButton();
        requires_button = new javax.swing.JButton();
        project_table = new javax.swing.JButton();
        has_degree_button = new javax.swing.JButton();
        log_button = new javax.swing.JButton();
        user_button = new javax.swing.JButton();
        job_button = new javax.swing.JButton();
        degree_button = new javax.swing.JButton();
        DBA_button = new javax.swing.JButton();
        evaluator_button = new javax.swing.JButton();
        got_the_job_button = new javax.swing.JButton();
        Employee_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();
        subject_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        employee_info_button = new javax.swing.JButton();
        evaluator_info_button = new javax.swing.JButton();
        application_process_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Main Frame");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        etaireia_table.setText("Etaireia");
        etaireia_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etaireia_tableActionPerformed(evt);
            }
        });

        applies_button.setText("Applies");
        applies_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applies_buttonActionPerformed(evt);
            }
        });

        promotion_log.setText("Promotion_log");
        promotion_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promotion_logActionPerformed(evt);
            }
        });

        languages_button.setText("Languages");
        languages_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languages_buttonActionPerformed(evt);
            }
        });

        requires_button.setText("Requires");
        requires_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requires_buttonActionPerformed(evt);
            }
        });

        project_table.setText("Project");
        project_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                project_tableActionPerformed(evt);
            }
        });

        has_degree_button.setText("Has_degree");
        has_degree_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                has_degree_buttonActionPerformed(evt);
            }
        });

        log_button.setText("Log");
        log_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_buttonActionPerformed(evt);
            }
        });

        user_button.setText("User ");
        user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_buttonActionPerformed(evt);
            }
        });

        job_button.setText("Job");
        job_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                job_buttonActionPerformed(evt);
            }
        });

        degree_button.setText("Degree");
        degree_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degree_buttonActionPerformed(evt);
            }
        });

        DBA_button.setText("DBA");
        DBA_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DBA_buttonActionPerformed(evt);
            }
        });

        evaluator_button.setText("Evaluator");
        evaluator_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluator_buttonActionPerformed(evt);
            }
        });

        got_the_job_button.setText("Got_the_job");
        got_the_job_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                got_the_job_buttonActionPerformed(evt);
            }
        });

        Employee_button.setText("Employee");
        Employee_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Employee_buttonActionPerformed(evt);
            }
        });

        close_button.setText("Exit");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });

        subject_button.setText("Subject");
        subject_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_buttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Additional Functions");

        employee_info_button.setText("Employee Info");
        employee_info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_info_buttonActionPerformed(evt);
            }
        });

        evaluator_info_button.setText("Evaluator Info");
        evaluator_info_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluator_info_buttonActionPerformed(evt);
            }
        });

        application_process_button.setText("Process Applications");
        application_process_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                application_process_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_button)
                            .addComponent(degree_button))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Employee_button)
                            .addComponent(languages_button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(evaluator_button)
                            .addComponent(etaireia_table))
                        .addGap(146, 146, 146))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(applies_button)
                                .addGap(18, 18, 18)
                                .addComponent(promotion_log))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(job_button)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(got_the_job_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(has_degree_button)
                                        .addGap(24, 24, 24)
                                        .addComponent(requires_button))
                                    .addComponent(DBA_button))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(subject_button)))
                        .addGap(153, 153, 153))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(project_table)
                        .addGap(18, 18, 18)
                        .addComponent(log_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close_button)
                        .addGap(35, 35, 35))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(employee_info_button)
                        .addGap(18, 18, 18)
                        .addComponent(evaluator_info_button)
                        .addGap(18, 18, 18)
                        .addComponent(application_process_button)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(user_button)
                        .addComponent(Employee_button)
                        .addComponent(evaluator_button))
                    .addComponent(DBA_button))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degree_button)
                    .addComponent(etaireia_table)
                    .addComponent(job_button)
                    .addComponent(languages_button))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(got_the_job_button)
                    .addComponent(has_degree_button)
                    .addComponent(requires_button)
                    .addComponent(subject_button))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(project_table)
                    .addComponent(log_button)
                    .addComponent(applies_button)
                    .addComponent(promotion_log)
                    .addComponent(close_button))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee_info_button)
                    .addComponent(evaluator_info_button)
                    .addComponent(application_process_button))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subject_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_buttonActionPerformed
        subject_frame subject = new subject_frame();
        subject.setVisible(true);
    }//GEN-LAST:event_subject_buttonActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        JFrame currentframe = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(currentframe, "Confirm if you want to exit.", "MySQL User",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
    {
        System.exit(0);
        }
    }//GEN-LAST:event_close_buttonActionPerformed

    private void Employee_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Employee_buttonActionPerformed
        employee_frame em = new employee_frame();
        em.setVisible(true);                  // TODO add your handling code here:
    }//GEN-LAST:event_Employee_buttonActionPerformed

    private void got_the_job_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_got_the_job_buttonActionPerformed
        got_the_job_frame gtj = new got_the_job_frame();
        gtj.setVisible(true);
    }//GEN-LAST:event_got_the_job_buttonActionPerformed

    private void evaluator_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluator_buttonActionPerformed
        evaluator_frame evaluator = new evaluator_frame();
        evaluator.setVisible(true);
    }//GEN-LAST:event_evaluator_buttonActionPerformed

    private void DBA_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DBA_buttonActionPerformed
        DBA_frame DBA = new DBA_frame();
        DBA.setVisible(true);
    }//GEN-LAST:event_DBA_buttonActionPerformed

    private void degree_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degree_buttonActionPerformed
        degree_frame degree = new degree_frame();
        degree.setVisible(true);
    }//GEN-LAST:event_degree_buttonActionPerformed

    private void job_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_job_buttonActionPerformed
        job_frame job = new job_frame();
        job.setVisible(true);
    }//GEN-LAST:event_job_buttonActionPerformed

    private void user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_buttonActionPerformed
        user_frame u = new user_frame();
        u.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_user_buttonActionPerformed

    private void log_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_buttonActionPerformed
        log_frame log = new log_frame();
        log.setVisible(true);
    }//GEN-LAST:event_log_buttonActionPerformed

    private void has_degree_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_has_degree_buttonActionPerformed
        has_degree_frame has_degree = new has_degree_frame();
        has_degree.setVisible(true);
    }//GEN-LAST:event_has_degree_buttonActionPerformed

    private void project_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_project_tableActionPerformed
        project_table project = new project_table();
        project.setVisible(true);
    }//GEN-LAST:event_project_tableActionPerformed

    private void requires_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requires_buttonActionPerformed
        requires_frame requires = new requires_frame();
        requires.setVisible(true);
    }//GEN-LAST:event_requires_buttonActionPerformed

    private void languages_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languages_buttonActionPerformed
        languages_frame languages = new languages_frame();
        languages.setVisible(true);
    }//GEN-LAST:event_languages_buttonActionPerformed

    private void promotion_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promotion_logActionPerformed
        promotion_log_frame promotion_log = new promotion_log_frame();
        promotion_log.setVisible(true);
    }//GEN-LAST:event_promotion_logActionPerformed

    private void applies_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applies_buttonActionPerformed
        applies_frame applies = new applies_frame();
        applies.setVisible(true);
    }//GEN-LAST:event_applies_buttonActionPerformed

    private void etaireia_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etaireia_tableActionPerformed
        etaireia_frame etaireia = new etaireia_frame();
        etaireia.setVisible(true);
    }//GEN-LAST:event_etaireia_tableActionPerformed

    private void employee_info_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_info_buttonActionPerformed
        employee_data_frame employee_data = new employee_data_frame();
        employee_data.setVisible(true);
    }//GEN-LAST:event_employee_info_buttonActionPerformed

    private void evaluator_info_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluator_info_buttonActionPerformed
        evaluator_data_frame evaluator_data = new evaluator_data_frame();
        evaluator_data.setVisible(true);
    }//GEN-LAST:event_evaluator_info_buttonActionPerformed

    private void application_process_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_application_process_buttonActionPerformed
        apply_processing_frame apply_processing = new apply_processing_frame();
        apply_processing.setVisible(true);
    }//GEN-LAST:event_application_process_buttonActionPerformed

    private JFrame frame;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DBA_button;
    private javax.swing.JButton Employee_button;
    private javax.swing.JButton application_process_button;
    private javax.swing.JButton applies_button;
    private javax.swing.JButton close_button;
    private javax.swing.JButton degree_button;
    private javax.swing.JButton employee_info_button;
    private javax.swing.JButton etaireia_table;
    private javax.swing.JButton evaluator_button;
    private javax.swing.JButton evaluator_info_button;
    private javax.swing.JButton got_the_job_button;
    private javax.swing.JButton has_degree_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton job_button;
    private javax.swing.JButton languages_button;
    private javax.swing.JButton log_button;
    private javax.swing.JButton project_table;
    private javax.swing.JButton promotion_log;
    private javax.swing.JButton requires_button;
    private javax.swing.JButton subject_button;
    private javax.swing.JButton user_button;
    // End of variables declaration//GEN-END:variables
}
